### ISSUE TITLE
Active rule (area?) overwrites manual deviating rwy selection in auto mode

### ISSUE THREAD

**Issue by Phil061995** [Gameagle/vSID#156]

**Comment by Phil7789** [comment]
So e.g. in EDDF
- somebody is parked in the south and with area south active runway 25L would be assigned but the atc rwy was 18. Now 25L is overwriting the before set rwy 18?
- somebody is parked in the east but rwy 18 was set before and with the rule that aircraft in the east should be cleared via rwy 25 now rwy 25 overwrites 18?

**Comment by Phil061995** [comment]
@Phil7789 Traffic parked in the east, rule "east25" active. It is not possible to select rwy 18 after 25 has been set initially, as this is always overwritten by 25 as soon as you try to set rwy 18.

**Comment by Phil7789** [comment]
Related #157

**Comment by Phil7789** [comment]
Able to reproduce now with disabled areas. As long as areas are active the runway selection is respected. Considered more an enhancement than a bug as the automode is working correctly, but it's an inconvenience for atc to not be able to change the runway away from the configuration.

**Comment by Phil7789** [comment]
e231b0f30c399f1760f0830fb555ceef4213d7a0
