### ISSUE TITLE
SID menu when no DRWY is selected

### ISSUE THREAD

**Issue by Phil061995** [Gameagle/vSID#212]
Maybe it would be possible to have a SID menü with all SIDs available for that specific when no DRWY is selected. Additionally the runway should be included in this kind of menu - like the ES SID menu.

This would reduce the clicks for manual SIDs as RWY and SID can be seleted out of one menu.

Potential problem, F/G SIDs out of EDDF where both designators are used for two different runways.

**Comment by Phil7789** [comment]
Option would be to "double" the SIDs. So SIDs with multiple runways would have multiple entries in the list.
