### ISSUE TITLE
[Feature Request] Changeable Colors

### ISSUE THREAD

**Issue by Backdraft81** [Gameagle/vSID#231]
Can you make the color of the table changeable? I can hardly distinguish green from blue in my view.

**Comment by Phil7789** [comment]
You can check https://github.com/Gameagle/vSID/blob/main/vSidConfig.json

The colors are defined by the NAV teams. Currently every color is changeable. There might be different configs for different profiles (like Tower or Radar).

**Comment by Backdraft81** [comment]
Thank you, perfect solution

Am Sa., 19. Okt. 2024 um 13:20 Uhr schrieb Phil7789 <
***@***.***>:
