### ISSUE TITLE
Initial climb not not appearing in the context menu

### ISSUE THREAD

**Issue by Ninovui** [Gameagle/vSID#252]
Hello !

Maybe this has already been covered before, but in the doubt I'll open a ticket.

I did my own config files for few french airport I'm controlling on and I noticed that some SIDs unexplicably doesn't pop up, while it should (flight plan correct and SID is auto displayed on the strip by default). I have no idea why it does that, knowing that for every other strip it pops as it should.

e.g. here's a SID that doesn't work on LFLL :

 "REPSI": {
        "1": {
            "designator": "S",
            "rwy": "17L, 17R",
            "initial": 7000,
            "prio": 1,
            "climbvia": true
        },
        "2": {
            "designator": "N",
            "rwy": "35L, 35R",
            "initial": 7000,
            "prio": 1,
            "climbvia": true
        }
    },
    
    I have similar issue for LFML too. I checked my JSON file twice or maybe more, but couldn't find a reason why it doesn't work.
    
    Any idea ? Thx !

**Comment by Phil7789** [comment]
Is it just the initial climb or the entire SID that is missing?
With v0.11.0 multiple runways should work correctly now (wasn't needed before so vSID was set to always choose the first runway), but I don't think this is related here.

If you wish feel free to attach your config file here

**Comment by Ninovui** [comment]
Hello !
Config file will follow later on today.
Well I did configure my departure list so I have the altitude suggested by vSID and by clicking it open the menu with available SIDs.
And in my case, when I click, the menu just says  something like « no available SID » or something like that. And I noticed it’s not displayed at anytime eg. while clearing a VFR aircraft. No idea why.

**Comment by Phil061995** [comment]
@Ninovui do you have some screenshots?

**Comment by Ninovui** [comment]
Oh and here's the config used for Marseille Provence :
[LFML.json](https://github.com/user-attachments/files/17966354/LFML.json)

**Comment by Phil061995** [comment]
@Ninovui I have found a } error at the "MAMES" SID in your file (that's why there was a warning, that MAMES could not be found in the .ese). You may try the following config. 
[LFML.json](https://github.com/user-attachments/files/17966441/LFML.json)

**Comment by Ninovui** [comment]
Ok, yes, there's no more error on the message bar...
I'll see if that fixed it. In case if that happens next, what should I do ?

**Comment by Ninovui** [comment]
Ok, I found my error. I forgot a bracket ( } ) and didn't noticed it.
Thank you for your support !
