### ISSUE TITLE
Startup Counter not deleted after relogin

### ISSUE THREAD

**Issue by Phil061995** [Gameagle/vSID#261]
After loggin off, the counter stays where it is. When ES is not closed and reconnect some time later, the old traffic that is not online anymore can't be deleted out of the counter.

**Comment by Phil7789** [comment]
Euroscope limitation as there is no information when the "Myself" Controller is disconnecting. Only other controllers can be checked for disconnection.
Also true for connecting to the network.

There is a possible workaround for this. Considered an enhancement rather than a bug.
