### ISSUE TITLE
Disregard "initial" when RFL below "initial"

### ISSUE THREAD

**Issue by gurselalp** [Gameagle/vSID#262]
![image](https://github.com/user-attachments/assets/a4c50333-0916-4186-9d3f-08785642a92d)

Plugin currently only checks "initial" value in the airport config. Sometimes we have cases like RFL below Initial climb altitude. If plugin checks the RFL as well and;

RFL>CFL use "initial" value
RFL<CFL use RFL value

for initial climb.

**Comment by Phil7789** [comment]
@gurselalp 
I've set it to monitor so you can evaluate if it meets your goals (current pre-release contains the feature).

A good idea but we suffer from Euroscope limitations (again). As ES reports the cleared altitude as the requested flight level if the cleared altitude is not set, now if a RFL is below the initial climb it will be shown and already color coded (so not white for suggestion anymore, mostly orange for custom climb).
